fig, axes = plt.subplots(2, 1)
data = pd.Series(np.random.rand(16), index=list('ABCDEFGHIJKLMNOP'))
data2 = pd.Series(np.random.rand(16), index=list('abcdefghijklmnop'))
data2.plot.bar(ax=axes[0], color='orange', alpha=0.7)
data.plot.bar(ax=axes[0], color='b', alpha=0.7)
data2.plot.barh(ax=axes[1], color='#0000ff', alpha=0.3)
axes[0].set_title('Vertical bars')
axes[1].set_title('Horizonal bars')
fig.tight_layout()
